[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core"]

[alias]
c6 = "run -p esp32c6-app --target riscv32imac-unknown-none-elf"
s3 = "run -p esp32s3-app --target xtensa-esp32s3-none-elf"
